# <font color='red'>NumPy</font>:Numerical Python
<ul>
    <li>NumPy is a Python Library which is used to perform different mathematical operations on arrays.</li>
    <li>Array is denoted with '[ ]' and homogenous(items of simillar data type )Collection of items</li>
</ul>

In [1]:
import numpy as np

In [2]:
# Creating 1-D Array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)  # ndarray :n-dimensional array

numpy.ndarray

In [4]:
b=np.array([2,3,'cat',3.4,3.5,True])
b

array(['2', '3', 'cat', '3.4', '3.5', 'True'], dtype='<U32')

In [6]:
b = np.array([20,46,3.2,True])
b

array([20. , 46. ,  3.2,  1. ])

In [7]:
# Tuple to array
t = np.array((1,2,3,4,5))
t

array([1, 2, 3, 4, 5])

In [8]:
# Set to array
s = np.array({10,84,65,68,98,654,654,65684})
s

array({65, 98, 68, 84, 65684, 10, 654}, dtype=object)

In [9]:
# Dictionary a Array
d = np.array({'a': 1, 'b': 2,'c': 3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [11]:
# Creating a 2-D Aray
a = np.array([[1,5,6],[5,3,7]])
a

array([[1, 5, 6],
       [5, 3, 7]])

In [13]:
# Array Attributes
a.shape

(2, 3)

In [14]:
a.size #to check total number of elements 

6

In [15]:
a.ndim # to check number of dimensions

2

In [17]:
np.arange(1,11) # Returns a 1-D array of given range/sequence

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
# zeros 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((5,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.zeros((5,5)).astype('int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
# ones
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
np.ones((3,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
#full
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [30]:
np.full((5,5),'🐭')

array([['🐭', '🐭', '🐭', '🐭', '🐭'],
       ['🐭', '🐭', '🐭', '🐭', '🐭'],
       ['🐭', '🐭', '🐭', '🐭', '🐭'],
       ['🐭', '🐭', '🐭', '🐭', '🐭'],
       ['🐭', '🐭', '🐭', '🐭', '🐭']], dtype='<U1')

In [31]:
#eye
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
#inspace - equally distributed numbers
np.linspace(1,100,15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])

In [33]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [34]:
# Random Numbers
np.random.rand()

0.802069688882355

In [35]:
np.random.rand(4)

array([0.0719952 , 0.18920326, 0.849311  , 0.13324567])

In [36]:
np.random.rand(3,4)

array([[0.26516145, 0.77609278, 0.33881169, 0.87510633],
       [0.98796009, 0.32337315, 0.08377664, 0.4161477 ],
       [0.13784282, 0.28727499, 0.84916021, 0.42747091]])

In [37]:
np.random.rand(3,4) * 100

array([[7.88770090e+01, 6.65354115e-02, 2.57913288e+01, 4.10956602e+01],
       [1.26532447e+01, 1.10861469e+01, 4.24973739e+01, 5.71049354e+00],
       [5.56695846e+01, 9.99518953e+01, 8.50826640e+01, 1.75411120e+01]])

In [38]:
np.random.randint(1,20)

15

In [41]:
np.random.randint(10,20,(4,3))

array([[16, 16, 15],
       [10, 17, 12],
       [18, 13, 14],
       [14, 10, 16]])

In [42]:
# Mathematical Operations
a = np.array([30,65,55,79,25])